version: '2'
services:
        jodconverter:
                build: jodconverter
                restart: always
                ports:
                        - 8080:8080       

        memcache:
                build: memcache
                restart: always
                
        mysql:
                build: mysql
                restart: always
                environment:
                        - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
                ports:
                        - 3306:3306
                volumes:
                        - /opt/volumes/mysql:/var/lib/mysql
        solr:
                build: solr
                restart: always
                ports:
                        - 8983:8983
                entrypoint:
                        - solr-precreate
                        - sei-protocolos
 
